Repository Vactor0911/fablab-booking-system-server, pull requests merged in 2025-01, with the labels that each got.

#1 Create README.md
  README.md
Labels: documentation

#2 로컬 데이터베이스 연동 및 라이브러리 설치
  index.ts
  package-lock.json
  package.json
Labels: 개선

#3 Hits
  admin.ts
  index.ts
  middleware/authenticate.ts
  package-lock.json
  package.json
Labels: 개선

#4 Hits
  index.ts
  middleware/authenticate.ts
  package-lock.json
  package.json
Labels: 개선

#5 좌석 예약 생성 관련 API 구현 및 수정
  index.ts
Labels: 개선

#6 Hits
  index.ts
Labels: 개선

#8 Dev
  admin.ts
  index.ts
  middleware/authenticate.ts
  package-lock.json
  package.json
Labels: 개선

#10 Hits
  index.ts
Labels: 개선

#12 Hits - CSRF 보안 토큰 필요한 API에 적용
  index.ts
  package-lock.json
  package.json
Labels: 개선

#14 Hits
  index.ts
Labels: 개선

#15 Dev
  index.ts
Labels: 개선

#16 주석 내 명칭 변경
  index.ts
Labels: 개선

#17 주석 내 명칭 변경
  index.ts
Labels: 개선

#18 Vactor0911
  .github/workflows/deploy.yml
  index.ts
Labels: 개선

#19 Dev
  .github/workflows/deploy.yml
  index.ts
Labels: 개선

#20 잘못 생성한 워크플로우 삭제
  workflow/deploy.yml
Labels: 버그

#22 깃허브 워크플로우 테스트
  TestFile
Labels: 오류 의심

#23 테스트용 파일 삭제
  TestFile
Labels: 오류 의심

#24 Hits
  index.ts
Labels: 개선

#26 유효성 검사 라이브러리 validator 추가
  index.ts
  package-lock.json
  package.json
Labels: 개선

#29 설명 추가 및 강제 퇴실 API 입력 데이터 수정
  admin.ts
Labels: 개선

#31 dev
  admin.ts
  package-lock.json
  package.json
Labels: 개선

#32 Dev
  admin.ts
  index.ts
  package-lock.json
  package.json
Labels: 개선

#33 Hits
  admin.ts
  index.ts
Labels: 개선

#35 사용자 목록 조회 API, 사용자 정보 수정 API
  admin.ts
  index.ts
  package-lock.json
  package.json
Labels: 개선

#36 Dev 사용자 목록 조회 API, 사용자 정보 수정 API
  admin.ts
  index.ts
  package-lock.json
  package.json
Labels: 개선

#37 Hits
  admin.ts
  image/group.png
  image/single.PNG
  image/windowIMAC.jpg
  image/windowSeat.jpg
  index.ts
  middleware/authenticate.ts
  package-lock.json
  package.json
Labels: 개선

#38 Dev
  admin.ts
  image/group.png
  image/single.PNG
  image/windowIMAC.jpg
  image/windowSeat.jpg
  index.ts
  middleware/authenticate.ts
  package-lock.json
  package.json
Labels: 개선

#40 Hits
  admin.ts
  index.ts
  package-lock.json
Labels: 개선

#41 Dev
  admin.ts
  index.ts
  package-lock.json
  package.json
Labels: 개선
